spring:
  application:
    name: currency-exchange-service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
